name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: json, libxml, mbstring
          ini-values: assert.exception=1, zend.assertions=1

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit
        run: vendor/bin/phpunit
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: "6379"
